1. Типы ошибок
2. Работа с кодами возврата

**Аннотация.** Урок посвящен ошибкам и их типам.

## Типы ошибок

Разработка программы на любом языке программирования практически всегда бывает связана с возникновением различного рода ошибок, препятствующих получению желаемого результата.

Обычно выделяют следующие три категории ошибок:

- синтаксические – возникают из-за синтаксических погрешностей кода
- логические – проявляются вследствие логических неточностей в алгоритме
- ошибки времени выполнения, исключения – вызваны некорректными действиями пользователя или системы

### Синтаксические ошибки

Синтаксические ошибки являются следствием несоблюдения общепринятого синтаксиса языка. Другими словами, это ошибки, связанные с неправильно набранным кодом. Например пропуск круглой скобки, запятой или двоеточия.

В приведенном ниже коде:

```python
print('Hello, world!'
```

допущена одна синтаксическая ошибка: **пропущена закрывающая скобка**. При попытке его запуска получим:

```no-highlight
SyntaxError: '(' was never closed
```

В приведенном ниже коде:

```python
def square(num)
    return num ** 2
```

допущена также синтаксическая ошибка: **пропущен символ двоеточия в описании функции**. При попытке его запуска получим:

```no-highlight
    def square(num)
                   ^
SyntaxError: expected ':'
```

![](https://ucarecdn.com/1b9f5d78-cbb1-453d-ac39-f6e480da169c/)Синтаксические ошибки легко отлавливаются интерпретатором, который сразу же сообщает программисту о проблеме в написанном коде. 

### Логические ошибки

Логические ошибки считаются более сложными в выявлении, поскольку не отлавливаются интерпретатором. Обычно они вызваны определенным недостатком в логике программы, из-за чего результат работы программы отличается от желаемого результата. Возможным решением проблемы является тестирование программы на разных примерах входных данных, для которых известен правильный результат.

В приведенном ниже коде:

```python
def avg(a, b):
    return a + b / 2
```

описана функция `avg()`, подсчитывающая среднее значение переданных в нее аргументов. В теле функции допущена логическая ошибка, пропущены скобки, на два должна делиться сумма чисел `a` и `b`.

Приведенный ниже код:

```python
print(avg(6, 14))
```

выводит **неверный результат**:

```no-highlight
13.0
```

Обратите внимание на то, что приведенная выше функция `avg()` не всегда работает неверно.

Приведенный ниже код:

```python
print(avg(0, 7))
```

выводит **верный результат**:

```no-highlight
3.5
```

![](https://ucarecdn.com/96d3d11e-f604-4251-b402-cca56094a0c8/)Логические ошибки могут проявлять себя только при определенных условиях. Часто код с логической ошибкой может работать достаточно долго.

### Ошибки времени выполнения

Исключения представляют собой еще один вид ошибок, которые проявляются в зависимости от наличия обстоятельств, меняющих ход выполнения программы. Исключения являются ошибками времени выполнения, возникающие в процессе выполнения программы и связанные с некорректностью переданных в программу данных, недоступностью ресурсов и т.д.

Приведенный ниже код:

```python
num1 = 10
num2 = 0

print(num1 / num2)
```

выводит:

```no-highlight
ZeroDivisionError: division by zero
```

Деление на ноль провоцирует исключительную ситуацию, которая приводит к аварийному завершению работы и выводу ошибки на экран. `ZeroDivisionError` — это название исключения, а `division by zero` — его краткое описание.

![](https://ucarecdn.com/ed64f67a-867b-424d-b173-de3608894f88/)Если мы хотим, чтобы программа работала с широким диапазоном входных данных и внешних условий, то надо учитывать исключения, программа должна их верно обрабатывать.

По умолчанию при обнаружении необработанного исключения Python немедленно останавливает выполнение программы и выводит сообщение об ошибке.

## Работа с кодами возврата

В эпоху расцвета процедурного программирования синтаксис работы с исключениями был тривиален и основывался на том, что вернула функция. Если функция возвращала `True` — все хорошо, если же `False` — то произошла ошибка. При этом сразу выделились два подхода к работе с ошибками:

- подход **два в одном** — функция возвращает `False` как для ожидаемой, так и для неожиданной ошибки. Такой подход как правило применялся в API общего назначения и коде пользовательских программ, когда большую часть ошибок можно было смело считать фатальными
- подход **разделения ошибок**, при котором функция возвращает `False` в случае неожиданной ошибки, а ожидаемую ошибку возвращает отдельным возвращаемым значением (числовым). Такой подход применялся в более надежном коде и подразумевал разделение на ожидаемые ошибки и неожиданные

![](https://ucarecdn.com/1216fe1d-70e2-4fb0-b27b-37cda581c6fe/)Для каждой ошибки можно придумать свой код возврата. Коды не должны совпадать с возможными обычными ответами.

Несмотря на то, что язык Python полностью поддерживает работу с исключениями, как с полноценными объектами, мы все же можем встретить следы работы с кодами возврата, которые Python унаследовал от языка C.

Строковый тип данных `str` содержит два похожих метода `find()` и `index()`. Оба метода выполняют одну и ту же работу, а именно ищут позицию первого вхождения подстроки в заданную строку. Однако в случае если подстрока не найдена, то поведение методов отличается. Метод `find()` использует механизм кодов возврата, в то время как метод `index()` возбуждает исключение.

Приведенный ниже код:

```python
text = 'Hello, world!'

print(text.find('w'))
print(text.find('a'))
```

выводит:

```
7
-1
```

Из-за того, что в строке `Hello, world!` нет символа `a`, нам было возвращено значение `−1`. Это и есть **код возврата**.

Приведенный ниже код:

```python
text = 'Hello, world!'

print(text.index('a'))
```

приводит к возникновению исключения:

```no-highlight
ValueError: substring not found
```

При работе с кодами возврата даже простая функция для обработки пользовательских данных обрастает дополнительным кодом, проверкой многих условий и «магическими» кодами возврата. Если функция с кодом возврата находится глубоко в стеке вызовов, то придется сделать так, чтобы ее правильно обрабатывала вся вышестоящая цепочка функций. Каждая из них должна принимать код и возвращать свой.

## Примечания

**Примечание 1.** У работы с исключениями есть преимущества перед кодами возврата. В современных языках программирования, таких как Python, C#, Java, GO и т.д., используются именно исключения.

**Примечание 2.** Приведем пример незаметной логической ошибки, которая присуща многим реализациям бинарного поиска (или сортировке слиянием). Для реализации алгоритма требуется находить середину некоторого отрезка `[low; high]`. Обычно это делают так:

```python
mid = (low + high) // 2
```

Для языка Python такой способ подсчета середины работает нормально, поскольку в Python реализована длинная арифметика. Но, скажем, в языке Java, где стандартные типы данных имеют ограничения, такой способ подсчета середины в некоторых случаях приводит к переполнению, поскольку сумма `low + high` выходит за размерность типа `int`.

Для решения проблемы можно воспользоваться вот таким приемом:

```python
mid = low + (high - low) // 2
```

Такая ошибка долгое время находилась в стандартной библиотеке языка Java из-за чего поиск и сортировка на особо больших массивах приводил к возникновению исключения `ArrayIndexOutOfBoundsException`. Подробнее можно почитать по [ссылке](https://ai.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html).

**Примечание 3.** В больших информационных системах у каждой ситуации, у штатной и нештатной, есть свои номера. Наиболее распространенные коды ошибок в сети Интернет:

- `404 Not Found` (не найдено)
- `503 Service Unavailable` (сервис недоступен)

При этом `200` — это код, возвращаемый серверами при успешном выполнении задания.

Подробнее прочитать про список кодов сети Интернет можно по [ссылке](https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP).

**Примечание 4.** Подробнее о синтаксических ошибках можно почитать по [ссылке](https://realpython.com/invalid-syntax-python/).

**Примечание 5.** Документация об ошибках и исключениях доступна по [ссылке](https://docs.python.org/3/tutorial/errors.html).

**Примечание 6.** Один из способов посмотреть, насколько полезны исключения, предусматривает сравнение кодовых стилей в Python и языках без исключений. Скажем, если мы хотим написать надежную программу на языке C, то обычно должны проверять возвращаемые значения или коды состояния после каждой операции, способной сбиться с пути, и распространять результаты проверок во время выполнения программы:

```cpp
doStuff() 
{
  if (doFirstThing() == ERROR)
    return ERROR;
  if (doNextThing() == ERROR)
    return ERROR;
  ...
  return doLastThing();
}

main() 
{
  if (doStuff() == ERROR)
    badEnding();
  else
    goodEnding();
}
```

На самом деле реалистичные программы на C часто содержат столько же кода, предназначенного для обнаружения ошибок, сколько и кода для выполнения фактической работы. Но в Python нам не придется писать такой код. Мы можем просто помещать произвольно крупные фрагменты программы внутрь обработчиков исключений и писать код, делающий действительную работу, предполагая, что обычно все будет хорошо:

```python
def doStuff():
    doFirstThing()
    doNextThing()
    doLastThing()


try:
    doStuff()
except:
    badEnding()
else:
    goodEnding()
```

Так как при возникновении исключения управление немедленно передается обработчику, нет нужды снабжать весь код защитой от ошибок, к тому же отсутствуют добавочные накладные расходы в плане производительности, связанные с выполнением всех проверок. Кроме того, поскольку интерпретатор Python выявляет ошибки автоматически, в первую очередь вашему коду часто нет необходимости вообще осуществлять проверки на предмет ошибок. В итоге исключения позволяют почти совершенно игнорировать необычные случаи и избегать написания кода проверки на предмет ошибок, который способен отвлечь от подлинных целей программы