## Преобразование строки в дату и время

Часто бывает нужно, чтобы пользователь ввел какую‑либо дату или время. Есть два пути, чтобы преобразовать введенные данные из строки:

- преобразовать данные самостоятельно
- преобразовывать данные с помощью метода `strptime()` типа `datetime` (о котором будет рассказано в следующем уроке)

### Самостоятельное преобразование данных

Приведенный ниже код:

```python
from datetime import date, time

day, month, year = input('Введите дату в формате ДД.ММ.ГГГГ').split('.')
hour, minute, second = input('Введите время в формате ЧЧ:ММ:СС').split(':')

my_date = date(int(year), int(month), int(day))        # создаем объект типа date
my_time = time(int(hour), int(minute), int(second))    # создаем объект типа time

print(my_date)
print(my_time)
```

преобразует данные из строки в дату и время и выводит:

```no-highlight
2021-11-13
21:34:59
```

То есть изначально мы предполагаем, что введенные дата и время имеют определенный формат. Используя строковый метод `split()`, мы разделяем дату через точку (можно было выбрать любой другой разделитель), а время — через двоеточие (`:`). После этого мы создаем дату/время из полученных данных.

Если пользователь введет данные в неправильном формате, то мы можем получить самые разные ошибки (исключения) — от `ValueError` до `IndexError`. К тому же, если мы вдруг решим изменить формат входных данных, нам придется существенно переписать код для преобразования строки в дату/время.

Рассмотрим ситуацию, когда пользователь вводит некорректную дату именно с точки зрения календаря. Если попытаться ввести дату 3131 февраля (31.02.202131.02.2021), то мы получим ошибку (исключение) `ValueError`:

```no-highlight
ValueError: day is out of range for month
```

Для того чтобы поймать и обработать исключение, в Python используется конструкция `try-except` (о которой будет рассказано в данном курсе). Код, который потенциально может сгенерировать ошибку (исключение), помещается в блок `try`, и ошибки (исключения) перехватываются в блоке `except`.

Рассмотрим следующий код:

```python
from datetime import date, time

try:
    day, month, year = input('Введите дату в формате ДД.ММ.ГГГГ').split('.')
    my_date = date(int(year), int(month), int(day))
    print(my_date)
except ValueError:
    print('Ошибка ввода')
```

Если теперь попытаться ввести дату 3131 февраля (31.02.202131.02.2021), то при создании объекта `date` возникнет ошибка (исключение), которая будет перехвачена в блоке `except`. В результате работы программа выведет:

```no-highlight
Ошибка ввода
```

Обратите внимание на то, что текст `Ошибка ввода` будет выводиться в двух случаях:

1. пользователь вместо чисел введет что-то другое, тогда функция `int()` не сможет преобразовать строку в число и возникнет ошибка (исключение) `ValueError`
2. пользователь введет числа, но они не составляют корректную дату или время

 ![](https://ucarecdn.com/1180ccd2-1543-4e71-9f2c-5b70921f2726/)   Мы будем подробно разбираться с исключениями в рамках этого курса, но чуть позже.

### Читаем данные, пока не ввели корректную дату (время)

Конструкцию `try-except` можно завернуть в цикл, чтобы читать данные до тех пор, пока не ввели корректную дату (время).

Приведенный ниже код читает данные до тех пор, пока пользователь не введет корректную дату в нужном формате:

```python
from datetime import date, time

while True:
    try:
        day, month, year = input('Введите дату в формате ДД.ММ.ГГГГ').split('.')

        my_date = date(int(year), int(month), int(day))

        print('Введена корректная дата:', my_date)
        break
    except ValueError:    # перехватываем ошибку типа ValueError
        print('Введенная дата не является корректной, попробуйте еще раз')
```

Обратите внимание на то, что указанный выше код устойчив лишь к ошибкам (исключениям) типа `ValueError`. Чтобы обработчик перехватывал любую ошибку (исключение), нужно опустить слово `ValueError`:

```python
from datetime import date, time

while True:
    try:
        day, month, year = input('Введите дату в формате ДД.ММ.ГГГГ').split('.')

        my_date = date(int(year), int(month), int(day))

        print('Введена корректная дата:', my_date)
        break
    except:      # перехватываем любую ошибку
        print('Введенная дата не является корректной, попробуйте еще раз')
```

### Преобразование строки в дату с помощью метода `fromisoformat()`

Самостоятельное преобразование данных из строки в объекты типа `date` и `time` оказывается довольно неудобным. Код получается достаточно громоздким и плохо расширяемым.

Для того чтобы преобразовать строку из ISO формата в объект даты (`date`) или в объект времени (`time`), можно использовать метод `fromisoformat()`.

Приведенный ниже код:

```python
from datetime import date, time

my_date = date.fromisoformat('2020-01-31')
my_time = time.fromisoformat('10:20:30')

print(my_date)
print(my_time)
print(type(my_date))
print(type(my_time))
```

выводит:

```no-highlight
2020-01-31
10:20:30
<class 'datetime.date'>
<class 'datetime.time'>
```

Метод `fromisoformat()` полезен на практике, однако у него есть серьезное ограничение: он работает только с датой и временем, записанными в ISO формате.

![](https://ucarecdn.com/8e44ad57-f28c-4991-a825-1fbc9dd5074d/)   Метод `fromisoformat()` был добавлен только в Python 3.7. Ранее он недоступен.

В следующем уроке мы изучим метод `strptime()` типа `datetime`, который позволяет преобразовать строку из любого формата в объекты даты и времени.